@startuml class
abstract class ProgramBase {
    + {abstract} start(args: string[])
}

class Program {
    - __argument_processor: ArgumentProcessorBase
}

abstract class ArgumentValidatorBase {
    + {abstract} validate(args: string[]): boolean
}

class ArgumentValidator {
}

abstract class ArgumentProcessorBase {
    + {abstract} process(args: string[])
}

class ArgumentProcessor {
    - __argument_validator: ArgumentValidatorBase
    - __password_generator: PasswordGeneratorBase
    - __terminal: TerminalBase
}

abstract class TerminalBase {
    + {abstract} show(message: string)
}

class Terminal {
}

abstract class PasswordGeneratorBase {
    + {abstract} generate(): string
}

class PasswordGenerator {
    - __password_length: int
    - __random_character_generator: RandomCharacterGenerator
    - __string_shuffler: StringShuffler
}

abstract class RandomCharacterGeneratorBase {
    + {abstract} generate_uppercase_character(): char
    + {abstract} generate_lowercase_character(): char
    + {abstract} generate_digit_character(): char
    + {abstract} generate_special_character(): char
    + {abstract} generate_allowed_character(): char
}

class RandomCharacterGenerator {
    - __uppercase_characters: String
    - __lowercase_characters: String
    - __digit_characters: String
    - __special_characters: String
    - __allowed_characters: String
}

abstract class StringShufflerBase {
    + {abstract} shuffle(characters: String): String
}

class StringShuffler {
}

ArgumentValidatorBase <|-- ArgumentValidator
ArgumentProcessorBase <|-- ArgumentProcessor
TerminalBase <|-- Terminal
PasswordGeneratorBase <|-- PasswordGenerator
RandomCharacterGeneratorBase <|-- RandomCharacterGenerator
StringShufflerBase <|-- StringShuffler
ProgramBase <|-- Program

Program *--l ArgumentProcessorBase

ArgumentProcessor *--l ArgumentValidatorBase
ArgumentProcessor *--d PasswordGeneratorBase
ArgumentProcessor *--r TerminalBase

PasswordGenerator *--l RandomCharacterGeneratorBase
PasswordGenerator *--r StringShufflerBase
@enduml